# Generated by Django 4.2.5 on 2023-12-25 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="start_date",
            field=models.DateField(
                blank=True,
                verbose_name=datetime.datetime(
                    2023, 12, 25, 18, 19, 21, 873599, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
