# Generated by Django 4.2.5 on 2023-12-26 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_budget_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="start_date",
            field=models.DateField(
                blank=True,
                verbose_name=datetime.datetime(
                    2023, 12, 26, 10, 40, 47, 952406, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
