# Generated by Django 4.2.5 on 2023-12-26 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_budget_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="start_date",
            field=models.DateField(
                blank=True,
                verbose_name=datetime.datetime(
                    2023, 12, 26, 12, 43, 50, 967643, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
