# Generated by Django 4.2.5 on 2023-12-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=50)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("length", models.IntegerField()),
                ("instructor", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=150)),
                ("price", models.IntegerField(default=10)),
            ],
        ),
    ]
